language: objective-c
osx_image: xcode8.2
xcode_workspace: Snooball.xcworkspace
xcode_scheme: Snooball

before_install: pod repo update master --silent && pod install
script: xcodebuild -workspace Snooball.xcworkspace -scheme Snooball build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO PROVISIONING_PROFILE="" | xcpretty && exit ${PIPESTATUS[0]}

